services:
  pixeldb-web-dev:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:8080"
    volumes:
      - .:/app
      - /app/node_modules